worker_processes auto;

events {
    worker_connections 1024;
}

http {
    log_format debug_json escape=json
        '{"event":"nginx_access",'
        '"time":"$time_iso8601",'
        '"method":"$request_method",'
        '"uri":"$request_uri",'
        '"status":"$status",'
        '"error_code":"$upstream_status",'
        '"upstream_status":"$upstream_status",'
        '"upstream_addr":"$upstream_addr",'
        '"host":"$host",'
        '"remote_addr":"$remote_addr",'
        '"request_body":"$request_body",'
        '"request_time":"$request_time",'
        '"upstream_response_time":"$upstream_response_time"}';

    access_log /var/log/nginx/access.log debug_json;

    include /etc/nginx/conf.d/*.conf;
}

stream {
    # ===== RabbitMQ =====
    upstream rabbitmq_backend {
        server nginx_rabbitmq:5672;
    }

    server {
        listen 6380;
        proxy_pass rabbitmq_backend;
    }

    # ===== Postgres =====
    upstream postgres_backend {
        server nginx_postgres:5432;
    }

    server {
        listen 5433;
        proxy_pass postgres_backend;
    }

    # ===== Redis =====
    upstream redis_backend {
        server nginx_redis:6379;
    }

    server {
        listen 6379;
        proxy_pass redis_backend;
    }
}
